FROM registry.redhat.io/rhelai1/instructlab-nvidia-rhel9:1.1-1724960989

ENV HOME=/tmp
ENV XDG_CACHE_HOME=/tmp
ENV XDG_CONFIG_HOME=/tmp
ENV XDG_DATA_HOME=/tmp
ENV TRITON_CACHE_DIR=/tmp
ENV HF_HOME=/tmp
ENV TRANSFORMERS_CACHE=/tmp
ENV PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"

ENTRYPOINT ["python"]

